global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-compliance-common
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-west-1
    - us-west-2
  reporting: true
 
tests:
  quickstart-compliance-commont1:
    parameter_input: quickstart-compliance-common-example-params1.json
    template_file: quickstart-compliance-common-example1.template
  quickstart-compliance-commont2:
    parameter_input: quickstart-compliance-common-example-params2.json
    template_file: quickstart-compliance-common-example2.template
